services:
  dataimportapi:
    image: ${DOCKER_REGISTRY-}dataimportapi
    build:
      context: .
      dockerfile: DataImportApi/Dockerfile
      
  dataimportconsole:
    image: ${DOCKER_REGISTRY-}dataimportconsole
    build:
      context: .
      dockerfile: DataImportConsole/Dockerfile

  accommodationtransformer:
    image: ${DOCKER_REGISTRY-}accommodationtransformer
    build:
      context: .
      dockerfile: AccommodationTransformer/Dockerfile

